export const TextList = [
  'And the Same to You',
  'The Angry Silence',
  'Beat Girl',
  'Bluebeards Ten Honeymoons',
  'Bottoms Up',
  'The Boy Who Stole a Million',
  'The Brides of Dracula',
  'The Bulldog Breed',
  'Carry On Constable',
  'The Challenge',
  'A Circle of Deception',
  'Circus of Horrors',
  'The City of the Dead',
  'Cone of Silence',
  'Conspiracy of Hearts',
  'The Criminal',
  'Crossroads to Crime',
  'The Day They Robbed the Bank of England',
  'Dead Lucky',
  'Dentist in the Chair',
  'Depth Charge',
  'Doctor in Love',
  'The Entertainer',
  'Escort for Hire',
  'Faces in the Dark',
  'Feet of Clay',
  'The Flesh and the Fiends',
  'Follow That Horse!',
  'Foxhole in Cairo',
  'A French Mistress',
  'The Full Treatment',
  'The Gentle Trap',
  'The Hand',
  'Hand in Hand',
  'The Hands of Orlac',
  'Hell Is a City',
  'His and Hers',
  'The House in Marsh Road',
  'Identity Unknown',
  'In the Nick',
  'Inn for Trouble',
  'Jackpot',
  'Jazz Boat',
  'Kidnapped',
  'The League of Gentlemen',
  'Lets Get Married',
  'Life Is a Circus',
  'Light Up the Sky!',
  'Linda',
  'Make Mine Mink',
  'Man in the Moon',
  'Man Who Couldnt Walk',
  'The Man Who Was Nobody',
  'The Millionairess',
  'Never Let Go',
  'Never Take Sweets from a Stranger',
  'Night Train for Inverness',
  'No Kidding',
  'Once More, with Feeling!',
  'Operation Cupid',
  'Oscar Wilde',
  'Peeping Tom',
  'Piccadilly Third Stop',
  'The Pure Hell of St Trinians',
  'The Running Jumping & Standing Still Film',
  'Sands of the Desert',
  'Saturday Night and Sunday Morning',
  'The Savage Innocents',
  'School for Scoundrels',
  'Sink the Bismarck!',
  'Sons and Lovers',
  'The Spiders Web',
].map((item) => item.slice(0, 6));
